### ISSUE TITLE
PDF generated with all blank fields

### ISSUE THREAD

**Issue by BobToninho** [Daxo32/autodichi#2]
Not sure if this is done on purpose, but the .pdf file is generated even if all the form fields are blank. 

If this is done on purpose, the intention is to make a template file downloadable?

**Comment by Daxo32** [comment]
Hi, actually that is allowed intentionally because maybe someone want to fill only a few fields.

For example could happen that someone want to fill only the personal info, and then write the motivation for moving in a second time.
